channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.9
  - pytorch
  - torchvision
  - einops
  - torchmetrics==0.11.0
  - wandb
  - timm
  - cyanure-mkl
  - pyyaml
  - scikit-learn
  - umap-learn
  - pandas
  - matplotlib
  - pytest
  - pip
  - pip:
      - kappaconfig==1.0.29
      - kappadata==1.0.99
      - kappaprofiler==1.0.9
