vars:
  public_data: /home/juergen/Learning/Studies/AI/2023WS/Practical Work in AI Master PR/Dev/data

# the account name is only used to describe from which account the run was started from
# this is more descriptive than the hostname as it also specifies who ran it
account_name: JThann

# path to store logs/checkpoints
output_path: /home/juergen/Learning/Studies/AI/2023WS/Practical Work in AI Master PR/Dev/data/out
# path where pretrained models are stored
# model_path: <MODEL_PATH>

# global datasets
global_dataset_paths:
  # imagenet1k: ${vars.public_data}/ImageNet/ImageNet1K
  # imagenet1k_msn1perclass_split1: ${vars.public_data}/ImageNet1K/imagenet1k_msn1perclass_split1
  # imagenet1k_msn1perclass_split2: ${vars.public_data}/ImageNet1K/imagenet1k_msn1perclass_split2
  # imagenet1k_msn1perclass_split3: ${vars.public_data}/ImageNet1K/imagenet1k_msn1perclass_split3
  # imagenet1k_msn2perclass_split1: ${vars.public_data}/ImageNet1K/imagenet1k_msn2perclass_split1
  # imagenet1k_msn2perclass_split2: ${vars.public_data}/ImageNet1K/imagenet1k_msn2perclass_split2
  # imagenet1k_msn2perclass_split3: ${vars.public_data}/ImageNet1K/imagenet1k_msn2perclass_split3
  # imagenet1k_msn5perclass_split1: ${vars.public_data}/ImageNet1K/imagenet1k_msn5perclass_split1
  # imagenet1k_msn5perclass_split2: ${vars.public_data}/ImageNet1K/imagenet1k_msn5perclass_split2
  # imagenet1k_msn5perclass_split3: ${vars.public_data}/ImageNet1K/imagenet1k_msn5perclass_split3
  # imagenet1k_msn1percent: ${vars.public_data}/ImageNet1K/imagenet1k_msn1percent
  # imagenet1k_10percent_simclrv2: ${vars.public_data}/ImageNet1K/imagenet1k_10percent_simclrv2
  # imagenet_a: ${vars.public_data}/ImageNet-A
  # imagenet_r: ${vars.public_data}/ImageNet-R
  # imagenet_v2: ${vars.public_data}/ImageNet-V2
  # imagenet15_dogs: ${vars.public_data}/ImageNet15/imagenet15_dogs
  imagenet10: ${vars.public_data}/ImageNet10/imagenet10_clustering
  cifar10: ${vars.public_data}/cifar-10-batches-py
  cifar100: ${vars.public_data}/cifar-100-python

# OPTIONAL: path to (fast) local storage
local_dataset_path: /media/SSD_Gaming/AI/maect

# wandb
# disabled -> don't use wandb
# offline -> use wandb in offline mode
# online -> use wandb in online mode
default_wandb_mode: online

# DDP
master_port: 55555

# cudnn
default_cudnn_benchmark: true
default_cudnn_deterministic: false
# enable/disable cuda profiling
# - enabled: after every cuda operation to be profiled a torch.cuda.synchronize and dist.barrier is appended -> slower
# - disabled: cuda operations are not profiled
default_cuda_profiling: false
# sync batchnorm
default_sync_batchnorm: true
