stage_name: 4stage_maect_noaug_linear_probing
datasets:
  train:
    kind: torchvision_dataset_wrapper
    dataset_identifier: cifar10
    num_classes: 10
    torchvision_args:
      kind: CIFAR10
      train: true
      download: false
    x_transform:
    - kind: kd_random_resized_crop
      size: 32
      scale:
      - 0.08
      - 1.0
      interpolation: bicubic
    - kind: random_horizontal_flip
    - kind: kd_cifar10_norm
  test:
    kind: torchvision_dataset_wrapper
    dataset_identifier: cifar10
    num_classes: 10
    torchvision_args:
      kind: CIFAR10
      train: false
      download: false
    x_transform:
    - kind: kd_cifar10_norm

model:
  kind: backbone_head
  backbone:
    kind: vit.vit_mae
    patch_size: 4
    embedding_dim: 192
    depth: 12
    attention_heads: 3
    is_frozen: true
    # initialize either from previous stage
    initializer:
      checkpoint: last
      kind: previous_run_initializer
      model_name: mae_contheads_vit.target_encoder
      stage_id: ???
      stage_name: stage3
      model_info: ema=0.9999
    # or from a weights file
#    initializer:
#      kind: pretrained_initializer
#      weights_file: maect_large16.th
  head:
    kind: heads.multi_linear_head
    initializers:
      default:
        kind: trunc_normal_initializer
        std: 0.01
    optimizers:
      sgd_lr01_wupcos_wd0:
        kind: sgd
        lr: 0.1
        momentum: 0.9
        schedule:
        - end_percent: 10.0
          kind: linear
        - kind: cosine_annealing
      sgd_lr009_wupcos_wd0:
        kind: sgd
        lr: 0.09
        momentum: 0.9
        schedule:
        - end_percent: 10.0
          kind: linear
        - kind: cosine_annealing
      sgd_lr008_wupcos_wd0:
        kind: sgd
        lr: 0.08
        momentum: 0.9
        schedule:
        - end_percent: 10.0
          kind: linear
        - kind: cosine_annealing
      sgd_lr007_wupcos_wd0:
        kind: sgd
        lr: 0.07
        momentum: 0.9
        schedule:
        - end_percent: 10.0
          kind: linear
        - kind: cosine_annealing
      sgd_lr006_wupcos_wd0:
        kind: sgd
        lr: 0.06
        momentum: 0.9
        schedule:
        - end_percent: 10.0
          kind: linear
        - kind: cosine_annealing
      sgd_lr005_wupcos_wd0:
        kind: sgd
        lr: 0.05
        momentum: 0.9
        schedule:
        - end_percent: 10.0
          kind: linear
        - kind: cosine_annealing
      sgd_lr004_wupcos_wd0:
        kind: sgd
        lr: 0.04
        momentum: 0.9
        schedule:
        - end_percent: 10.0
          kind: linear
        - kind: cosine_annealing
      sgd_lr003_wupcos_wd0:
        kind: sgd
        lr: 0.03
        momentum: 0.9
        schedule:
        - end_percent: 10.0
          kind: linear
        - kind: cosine_annealing
      sgd_lr002_wupcos_wd0:
        kind: sgd
        lr: 0.02
        momentum: 0.9
        schedule:
        - end_percent: 10.0
          kind: linear
        - kind: cosine_annealing
      sgd_lr001_wupcos_wd0:
        kind: sgd
        lr: 0.01
        momentum: 0.9
        schedule:
        - end_percent: 10.0
          kind: linear
        - kind: cosine_annealing
    poolings:
      cls:
        # use CLS token
        kind: class_token
        # average pooling
        # kind: mean_patch

trainer:
  kind: classification_trainer
  max_epochs: 50
  effective_batch_size: 1024
  precision: bfloat16
  log_every_n_epochs: 1
  loggers:
  - kind: accuracy_logger
    every_n_epochs: 1
    dataset_key: test
  - kind: checkpoint_logger
    save_latest_optim: false
    save_optim: false
  - kind: best_model_logger
    every_n_epochs: 1
    metric_key: accuracy1/test/cls_sgd_lr01_wupcos_wd0_default
    model_name: backbone_head.head.cls_sgd_lr01_wupcos_wd0_default
  - kind: best_model_logger
    every_n_epochs: 1
    metric_key: accuracy1/test/cls_sgd_lr009_wupcos_wd0_default
    model_name: backbone_head.head.cls_sgd_lr009_wupcos_wd0_default
  - kind: best_model_logger
    every_n_epochs: 1
    metric_key: accuracy1/test/cls_sgd_lr008_wupcos_wd0_default
    model_name: backbone_head.head.cls_sgd_lr008_wupcos_wd0_default
  - kind: best_model_logger
    every_n_epochs: 1
    metric_key: accuracy1/test/cls_sgd_lr007_wupcos_wd0_default
    model_name: backbone_head.head.cls_sgd_lr007_wupcos_wd0_default
  - kind: best_model_logger
    every_n_epochs: 1
    metric_key: accuracy1/test/cls_sgd_lr006_wupcos_wd0_default
    model_name: backbone_head.head.cls_sgd_lr006_wupcos_wd0_default
  - kind: best_model_logger
    every_n_epochs: 1
    metric_key: accuracy1/test/cls_sgd_lr005_wupcos_wd0_default
    model_name: backbone_head.head.cls_sgd_lr005_wupcos_wd0_default
  - kind: best_model_logger
    every_n_epochs: 1
    metric_key: accuracy1/test/cls_sgd_lr004_wupcos_wd0_default
    model_name: backbone_head.head.cls_sgd_lr004_wupcos_wd0_default
  - kind: best_model_logger
    every_n_epochs: 1
    metric_key: accuracy1/test/cls_sgd_lr003_wupcos_wd0_default
    model_name: backbone_head.head.cls_sgd_lr003_wupcos_wd0_default
  - kind: best_model_logger
    every_n_epochs: 1
    metric_key: accuracy1/test/cls_sgd_lr002_wupcos_wd0_default
    model_name: backbone_head.head.cls_sgd_lr002_wupcos_wd0_default
  - kind: best_model_logger
    every_n_epochs: 1
    metric_key: accuracy1/test/cls_sgd_lr001_wupcos_wd0_default
    model_name: backbone_head.head.cls_sgd_lr001_wupcos_wd0_default

summary_summarizers:
- kind: best_metric_summary_summarizer
  pattern: accuracy1/test*/last
- kind: best_metric_summary_summarizer
  pattern: accuracy1/test*/max
- kind: best_metric_summary_summarizer
  pattern: accuracy1/test/cls_*/last
- kind: best_metric_summary_summarizer
  pattern: accuracy1/test/cls_*/max