stage_name: 3stage_semppl_fixmatch_stage2_semppl
datasets:
  train:
    kind: image_net
    version: imagenet10
    split: train
    dataset_wrappers:
      # - kind: classwise_subset_wrapper
      #   end_index: 120
      - kind: subset_wrapper
        end_index: 12
      - kind: semisupervised_wrapper
        labeled_percentage: 10
    sample_wrappers:
      - kind: multi_crop_wrapper
        transform_configs:
          - n_views: 4
            transforms:
              - interpolation: bicubic
                kind: kd_random_resized_crop
                scale:
                  - 0.08
                  - 1.0
                size: 224
              - kind: kd_random_horizontal_flip
              - brightness: 0.4
                contrast: 0.4
                hue: 0.1
                kind: kd_random_color_jitter
                p: 0.8
                saturation: 0.2
              - kind: kd_random_gaussian_blur_pil
                p: 0.1
                sigma:
                  - 0.1
                  - 2.0
              - kind: kd_random_grayscale
                p: 0.2
              - kind: kd_image_net_norm
          - n_views: 2
            transforms:
              - interpolation: bicubic
                kind: kd_random_resized_crop
                scale:
                  - 0.08
                  - 1.0
                size: 96
              - kind: kd_random_horizontal_flip
              - brightness: 0.4
                contrast: 0.4
                hue: 0.1
                kind: kd_random_color_jitter
                p: 0.8
                saturation: 0.2
              - kind: kd_random_gaussian_blur_pil
                p: 0.1
                sigma:
                  - 0.1
                  - 2.0
              - kind: kd_random_grayscale
                p: 0.2
              - kind: kd_image_net_norm
  test:
    kind: image_net
    version: imagenet10
    split: val
    dataset_wrappers:
      # - kind: classwise_subset_wrapper
      #   end_index: 50
      - kind: subset_wrapper
        end_index: 12
    sample_wrappers:
      - kind: multi_crop_wrapper
        transform_configs:
          - n_views: 4
            transforms:
              - interpolation: bicubic
                kind: kd_random_resized_crop
                scale:
                  - 0.08
                  - 1.0
                size: 224
              - kind: kd_random_horizontal_flip
              - brightness: 0.4
                contrast: 0.4
                hue: 0.1
                kind: kd_random_color_jitter
                p: 0.8
                saturation: 0.2
              - kind: kd_random_gaussian_blur_pil
                p: 0.1
                sigma:
                  - 0.1
                  - 2.0
              - kind: kd_random_grayscale
                p: 0.2
              - kind: kd_image_net_norm
          - n_views: 2
            transforms:
              - interpolation: bicubic
                kind: kd_random_resized_crop
                scale:
                  - 0.08
                  - 1.0
                size: 96
              - kind: kd_random_horizontal_flip
              - brightness: 0.4
                contrast: 0.4
                hue: 0.1
                kind: kd_random_color_jitter
                p: 0.8
                saturation: 0.2
              - kind: kd_random_gaussian_blur_pil
                p: 0.1
                sigma:
                  - 0.1
                  - 2.0
              - kind: kd_random_grayscale
                p: 0.2
              - kind: kd_image_net_norm
model:
  kind: mae_contheads_vit
  target_factor: 0.99
  encoder:
    kind: vit.masked_encoder
    patch_size: 16
    depth: 12
    embedding_dim: 768
    attention_heads: 12
    optim:
      kind: adamw
      lr: 0.0001
      weight_decay: 0.05
      betas:
        - 0.9
        - 0.95
      schedule:
        - end_percent: 20
          exclude_first: true
          exclude_last: true
          kind: linear_increasing
        - exclude_last: true
          kind: cosine_decreasing
    initializer:
      checkpoint: last
      kind: previous_run_initializer
      model_name: mae_contheads_vit.encoder
      stage_id: ???
      stage_name: stage1_mae
  contrastive_heads:
    semppl:
      kind: contrastive_heads.semppl_ema_queue_head
      proj_hidden_dim: 2048
      pred_hidden_dim: 4096
      output_dim: 256
      queue_size: 2560
      temperature: 0.15
      target_factor: 0.99
      pooling:
        kind: mean_patch
      optim:
        kind: adamw
        lr: 0.0001
        betas:
          - 0.9
          - 0.95
        weight_decay: 1.0e-05
        schedule:
          - end_percent: 20
            exclude_first: true
            exclude_last: true
            kind: linear_increasing
          - exclude_last: true
            kind: cosine_decreasing
      topk: 1
      random_queue_label_init: true
      n_classes: 10
      num_semantic_positives: 3
      num_queues: 4
      num_large_views: 4
      num_small_views: 2
      num_negatives: 10
      alpha: 0.2
      lambda_: 5
      c: 0.3
trainer:
  kind: mae_contheads_vit_trainer
  max_epochs: 5
  effective_batch_size: 12
  precision: bfloat16
  mask_generator:
    kind: random_mask_generator
    mask_ratio: 0.0
  normalize_pixels: true
  log_every_n_epochs: 1
  loggers:
    - every_n_epochs: 1
      kind: group_update_output_logger
      pattern: pseudo_label_acc
      invert_key: false
      category: loss
    - kind: group_update_output_logger
      every_n_samples: 2560
      pattern: nn_accuracy
    - every_n_epochs: 1
      kind: group_update_output_logger
      pattern: nn_accuracy
    - every_n_epochs: 1
      kind: group_update_output_logger
      pattern: L_augm
      invert_key: false
      category: loss
    - every_n_epochs: 1
      kind: group_update_output_logger
      pattern: L_sempos
      invert_key: false
      category: loss
    - every_n_epochs: 1
      kind: group_update_output_logger
      pattern: L_SemPPL_wo_inv_pen
      invert_key: false
      category: loss
    - every_n_epochs: 1
      kind: group_update_output_logger
      pattern: I_augm
      invert_key: false
      category: loss
    - every_n_epochs: 1
      kind: group_update_output_logger
      pattern: I_sempos
      invert_key: false
      category: loss
    - every_n_epochs: 1
      kind: group_update_output_logger
      pattern: vote_confidence
      invert_key: false
      category: pseudo_labeling
    - every_n_epochs: 1
      kind: group_update_output_logger
      pattern: known_label_count
      invert_key: false
      category: pseudo_labeling
    - every_n_epochs: 1
      kind: group_update_output_logger
      pattern: known_label_acc
      invert_key: false
      category: pseudo_labeling
    - every_n_epochs: 1
      kind: group_update_output_logger
      pattern: unknown_label_count
      invert_key: false
      category: pseudo_labeling
    - every_n_epochs: 1
      kind: group_update_output_logger
      pattern: unknown_label_acc
      invert_key: false
      category: pseudo_labeling
    - every_n_epochs: 1
      kind: group_update_output_logger
      pattern: thresholded_label_count
      invert_key: false
      category: pseudo_labeling
    - every_n_epochs: 1
      kind: group_update_output_logger
      pattern: thresholded_label_acc
      invert_key: false
      category: pseudo_labeling
    - kind: loss_logger
      every_n_epochs: 1
      dataset_key: test
    - kind: checkpoint_logger
      every_n_epochs: 10
    - kind: ema_logger
      every_n_epochs: 10
      model_paths:
        - encoder
      target_factors:
        - 0.9999
