stage_name: 2stage_mae_fixmatch_stage2_fixmatch_1p
datasets:
  train:
    kind: torchvision_dataset_wrapper
    dataset_identifier: cifar10
    num_classes: 10
    torchvision_args:
      kind: CIFAR10
      train: true
      download: false
    dataset_wrappers:
      # - kind: classwise_subset_wrapper
      #   end_index: 130
      - kind: semisupervised_wrapper
        labeled_percentage: 1
      - kind: semisupervised_oversampling_wrapper
        include_labeled_in_unlabeled: true
        unlabeled_to_labeled_ratio: 7
    sample_wrappers:
      - kind: multi_view_wrapper
        transforms:
          - - kind: kd_random_horizontal_flip
            - kind: kd_random_crop
              size: 32
              padding: 4
              padding_mode: reflect
            - kind: kd_cifar10_norm
          - - kind: kd_random_horizontal_flip
            - kind: kd_random_crop
              size: 32
              padding: 4
              padding_mode: reflect
            - kind: kd_rand_augment
              num_ops: 2
              magnitude: 10
              interpolation: bicubic
              fill_color: [ 125, 123, 114 ]
            - kind: kd_cifar10_norm
  test:
    kind: torchvision_dataset_wrapper
    dataset_identifier: cifar10
    torchvision_args:
      kind: CIFAR10
      train: false
      download: false
    num_classes: 10
    x_transform:
      - kind: kd_cifar10_norm
model:
  kind: mae_contheads_vit
  target_factor: 0.99
  encoder:
    kind: vit.masked_encoder
    patch_size: 4
    embedding_dim: 192
    depth: 12
    attention_heads: 3
    optim:
      kind: adamw
      lr: 0.0001
      weight_decay: 0.05
      betas:
        - 0.9
        - 0.95
      schedule:
        - end_percent: 20
          exclude_first: true
          exclude_last: true
          kind: linear_increasing
        - exclude_last: true
          kind: cosine_decreasing
    initializer:
      checkpoint: last
      kind: previous_run_initializer
      model_name: mae_contheads_vit.encoder
      stage_id: x8loap89
      stage_name: stage1_mae
  contrastive_heads:
    fixmatch:
      kind: heads.fixmatch_head
      target_factor: 0.99
      nonaffine_batchnorm: true
      output_shape: 10
      threshold: 0.0
      unsupervised_loss_weight: 1
      teacher_pseudo_labeling: true
      pooling:
        kind: class_token
        # kind: mean_patch
      optim:
        kind: adamw
        lr: 0.0001
        betas:
          - 0.9
          - 0.95
        weight_decay: 1.0e-05
        schedule:
          - end_percent: 20
            exclude_first: true
            exclude_last: true
            kind: linear_increasing
          - exclude_last: true
            kind: cosine_decreasing
      initializer:
        kind: trunc_normal_initializer
        std: 0.01
trainer:
  kind: mae_contheads_vit_trainer
  max_epochs: 100
  effective_batch_size: 128
  precision: bfloat16
  mask_generator:
    kind: random_mask_generator
    mask_ratio: 0.0
  normalize_pixels: true
  log_every_n_epochs: 1
  loggers:
    - every_n_epochs: 1
      kind: group_update_output_logger
      pattern: supervised_loss
      invert_key: false
      category: loss
    - every_n_epochs: 1
      kind: group_update_output_logger
      pattern: unsupervised_loss
      invert_key: false
      category: loss
    - every_n_epochs: 1
      kind: group_update_output_logger
      pattern: unsupervised_loss_mean_over_threshold
      invert_key: false
      category: loss
    - every_n_epochs: 1
      kind: group_update_output_logger
      pattern: samples_above_threshold
      invert_key: false
      category: confidence
    - every_n_epochs: 1
      kind: group_update_output_logger
      pattern: classification_confidence_unlabeled
      invert_key: false
      category: confidence
    - every_n_epochs: 1
      kind: group_update_output_logger
      pattern: classification_confidence_unlabeled_over_threshold
      invert_key: false
      category: confidence
    - every_n_epochs: 1
      kind: group_update_output_logger
      pattern: classification_confidence_labeled
      invert_key: false
      category: confidence
    - every_n_epochs: 1
      kind: group_update_output_logger
      pattern: pseudo_label_accuracy
      invert_key: false
      category: confidence
    - kind: accuracy_logger
      every_n_epochs: 1
      dataset_key: test
      predict_kwargs:
        views:
          - 0
        dataset_key: test
    - kind: loss_logger
      every_n_epochs: 1
      dataset_key: test
    - kind: checkpoint_logger
      every_n_epochs: 10
    - kind: best_metric_logger
      every_n_epochs: 1
      pattern: accuracy1/train*
    - kind: best_metric_logger
      every_n_epochs: 1
      pattern: accuracy1/train*
      log_absolute_best: true
    - kind: best_metric_logger
      every_n_epochs: 1
      pattern: accuracy1/test*
    - kind: best_metric_logger
      every_n_epochs: 1
      pattern: accuracy1/test*
      log_absolute_best: true
summary_summarizers:
  - kind: best_metric_summary_summarizer
    pattern: accuracy1/train*/last
  - kind: best_metric_summary_summarizer
    pattern: accuracy1/train*/max
  - kind: best_metric_summary_summarizer
    pattern: accuracy1/test*/last
  - kind: best_metric_summary_summarizer
    pattern: accuracy1/test*/max
