vars:
  label_percentage: 0.01
  lr: 0.001
  weight_decay: 0.05
  beta2: 0.999
  layerwise_lr_decay: 0.65
  warmup_epochs: 5
  max_epochs: 100
  randaug_num_ops: 2
  randaug_magnitude1: 2
  randaug_magnitude2: 4
  randaug_magnitude_std: 0.5
  randaug_apply_op_p: 1
  # mixup: 0.8
  # cutmix: 1.0
  # drop_path: 0

stage_name: 3stage_semppl_stage2_semppl
datasets:
  train:
    kind: torchvision_dataset_wrapper
    dataset_identifier: cifar10
    num_classes: 10
    torchvision_args:
      kind: CIFAR10
      train: true
      download: false
    dataset_wrappers:
      - kind: semisupervised_wrapper
        labeled_percentage: ${eval:${vars.label_percentage} * 100}
      - kind: semisupervised_oversampling_wrapper
        include_labeled_in_unlabeled: true
        unlabeled_to_labeled_ratio: 7
    sample_wrappers:
      - kind: multi_crop_wrapper
        transform_configs:
          - n_views: 2
            transforms:
              - interpolation: bicubic
                kind: kd_random_resized_crop
                scale:
                  - 0.14
                  - 1.0
                size: 32
              - kind: kd_rand_augment
                num_ops: ${vars.randaug_num_ops}
                magnitude: ${vars.randaug_magnitude1}
                magnitude_std: ${vars.randaug_magnitude_std}
                apply_op_p: ${vars.randaug_apply_op_p}
                interpolation: bicubic
                fill_color: [ 125, 123, 114 ]
              - kind: kd_cifar10_norm
          - n_views: 2
            transforms:
              - interpolation: bicubic
                kind: kd_random_resized_crop
                scale:
                  - 0.14
                  - 1.0
                size: 32
              - kind: kd_rand_augment
                num_ops: ${vars.randaug_num_ops}
                magnitude: ${vars.randaug_magnitude2}
                magnitude_std: ${vars.randaug_magnitude_std}
                apply_op_p: ${vars.randaug_apply_op_p}
                interpolation: bicubic
                fill_color: [ 125, 123, 114 ]
              - kind: kd_cifar10_norm
          - n_views: 1
            transforms:
              - interpolation: bicubic
                kind: kd_random_resized_crop
                scale:
                  - 0.05
                  - 0.14
                size: 16
              - kind: kd_rand_augment
                num_ops: ${vars.randaug_num_ops}
                magnitude: ${vars.randaug_magnitude1}
                magnitude_std: ${vars.randaug_magnitude_std}
                apply_op_p: ${vars.randaug_apply_op_p}
                interpolation: bicubic
                fill_color: [ 125, 123, 114 ]
              - kind: kd_cifar10_norm
          - n_views: 1
            transforms:
              - interpolation: bicubic
                kind: kd_random_resized_crop
                scale:
                  - 0.05
                  - 0.14
                size: 16
              - kind: kd_rand_augment
                num_ops: ${vars.randaug_num_ops}
                magnitude: ${vars.randaug_magnitude2}
                magnitude_std: ${vars.randaug_magnitude_std}
                apply_op_p: ${vars.randaug_apply_op_p}
                interpolation: bicubic
                fill_color: [ 125, 123, 114 ]
              - kind: kd_cifar10_norm
model:
  kind: mae_contheads_vit
  target_factor: 0.99
  encoder:
    kind: vit.masked_encoder
    patch_size: 4
    embedding_dim: 192
    depth: 12
    attention_heads: 3
    optim:
      kind: adamw
      lr: ${vars.lr}
      weight_decay: ${vars.weight_decay}
      betas:
        - 0.9
        - ${vars.beta2}
      param_group_modifiers:
        - decay: ${vars.layerwise_lr_decay}
          kind: layerwise_lr_decay_modifier
      schedule:
        - end_checkpoint:
            epoch: ${vars.warmup_epochs}
          exclude_first: true
          exclude_last: true
          kind: linear_increasing
        - exclude_last: true
          kind: cosine_decreasing
    initializer:
      checkpoint: last
      kind: previous_run_initializer
      model_name: mae_contheads_vit.encoder
      stage_id: x8loap89
      stage_name: stage1_mae
  contrastive_heads:
    semppl:
      kind: contrastive_heads.semppl_ema_queue_head
      proj_hidden_dim: 512
      pred_hidden_dim: 1024
      output_dim: 64
      queue_size: 2560
      temperature: 0.15
      target_factor: 0.99
      pooling:
        kind: mean_patch
      optim:
        kind: adamw
        lr: ${vars.lr}
        betas:
          - 0.9
          - ${vars.beta2}
        weight_decay: ${vars.weight_decay}
        schedule:
          - end_checkpoint:
              epoch: ${vars.warmup_epochs}
            exclude_first: true
            exclude_last: true
            kind: linear_increasing
          - exclude_last: true
            kind: cosine_decreasing
      topk: 1
      num_semantic_positives: 3
      num_queues: 4
      num_large_views: 4
      num_small_views: 2
      num_negatives: 10
      alpha: 0.2
      lambda_: 5
      c: 0.3
trainer:
  kind: mae_contheads_vit_trainer
  max_epochs: ${vars.max_epochs}
  effective_batch_size: 128
  precision: bfloat16
  mask_generator:
    kind: random_mask_generator
    mask_ratio: 0.0
  normalize_pixels: true
  log_every_n_epochs: 1
  loggers:
    - every_n_epochs: 1
      kind: group_update_output_logger
      pattern: pseudo_label_acc
      invert_key: false
      category: loss
    - kind: group_update_output_logger
      every_n_samples: 2560
      pattern: nn_accuracy
    - every_n_epochs: 1
      kind: group_update_output_logger
      pattern: nn_accuracy
    - every_n_epochs: 1
      kind: group_update_output_logger
      pattern: L_augm
      invert_key: false
      category: loss
    - every_n_epochs: 1
      kind: group_update_output_logger
      pattern: L_sempos
      invert_key: false
      category: loss
    - every_n_epochs: 1
      kind: group_update_output_logger
      pattern: L_SemPPL_wo_inv_pen
      invert_key: false
      category: loss
    - every_n_epochs: 1
      kind: group_update_output_logger
      pattern: I_augm
      invert_key: false
      category: loss
    - every_n_epochs: 1
      kind: group_update_output_logger
      pattern: I_sempos
      invert_key: false
      category: loss
    - every_n_epochs: 1
      kind: group_update_output_logger
      pattern: vote_confidence
      invert_key: false
      category: pseudo_labeling
    - every_n_epochs: 1
      kind: group_update_output_logger
      pattern: known_label_count
      invert_key: false
      category: pseudo_labeling
    - every_n_epochs: 1
      kind: group_update_output_logger
      pattern: known_label_acc
      invert_key: false
      category: pseudo_labeling
    - every_n_epochs: 1
      kind: group_update_output_logger
      pattern: unknown_label_count
      invert_key: false
      category: pseudo_labeling
    - every_n_epochs: 1
      kind: group_update_output_logger
      pattern: unknown_label_acc
      invert_key: false
      category: pseudo_labeling
    - every_n_epochs: 1
      kind: group_update_output_logger
      pattern: thresholded_label_count
      invert_key: false
      category: pseudo_labeling
    - every_n_epochs: 1
      kind: group_update_output_logger
      pattern: thresholded_label_acc
      invert_key: false
      category: pseudo_labeling
    - kind: checkpoint_logger
      every_n_epochs: 10
    - kind: ema_logger
      every_n_epochs: 10
      model_paths:
        - encoder
      target_factors:
        - 0.99
