vars:
  indices:
    - 21
    - 214
name: SampleLogger

stage_name: umap
ignore_stage_name: true
num_workers: 0
datasets:
  train:
    kind: torchvision_dataset_wrapper
    dataset_identifier: cifar100
    num_classes: 100
    torchvision_args:
      kind: CIFAR100
      train: true
      download: false
    dataset_wrappers:
      - kind: subset_wrapper
        end_index: 128
    sample_wrappers:
      - kind: x_transform_wrapper
        transform:
          - kind: kd_cifar100_norm
  test:
    kind: torchvision_dataset_wrapper
    dataset_identifier: cifar100
    num_classes: 100
    torchvision_args:
      kind: CIFAR100
      train: false
      download: false
    dataset_wrappers:
      - kind: class_filter_wrapper
        valid_classes:
          - 0
          - 1
          - 2
          - 3
          - 4
          - 5
          - 6
          - 7
          - 8
          - 9
    sample_wrappers:
      - kind: x_transform_wrapper
        transform:
          - kind: to_tensor
model:
  kind: backbone_head
  backbone:
    kind: vit.vit_mae
    patch_size: 4
    embedding_dim: 192
    depth: 12
    attention_heads: 3
    is_frozen: true
    # drop_path_rate: ${vars.drop_path}
  head:
    kind: heads.linear_head
    nonaffine_batchnorm: true
    pooling:
      kind: class_token
      # kind: mean_patch
    optim:
      kind: adamw
      lr: 0.001
      weight_decay: 0.05
      betas:
        - 0.9
        - 0.999
      schedule:
        - exclude_last: true
          kind: cosine_decreasing
trainer:
  kind: classification_trainer
  max_epochs: 1
  effective_batch_size: 128
  precision: bfloat16
  log_every_n_epochs: 1
  loggers:
    - kind: sample_logger
      dataset_key: test
      every_n_epochs: 1
      indices: ${vars.indices}