stage_name: stage2
datasets:
  train:
    kind: image_net
    version: imagenet1k
    split: train
    sample_wrappers:
      - kind: multi_view_wrapper
        transforms:
          - - interpolation: bicubic
              kind: kd_random_resized_crop
              scale:
                - 0.08
                - 1.0
              size: 224
            - kind: kd_random_horizontal_flip
            - brightness: 0.4
              contrast: 0.4
              hue: 0.1
              kind: kd_random_color_jitter
              p: 0.8
              saturation: 0.2
            - kind: kd_gaussian_blur_pil
              sigma:
                - 0.1
                - 2.0
            - kind: kd_random_grayscale
              p: 0.2
            - kind: kd_image_net_norm
          - - interpolation: bicubic
              kind: kd_random_resized_crop
              scale:
                - 0.08
                - 1.0
              size: 224
            - kind: kd_random_horizontal_flip
            - brightness: 0.4
              contrast: 0.4
              hue: 0.1
              kind: kd_random_color_jitter
              p: 0.8
              saturation: 0.2
            - kind: kd_random_gaussian_blur_pil
              p: 0.1
              sigma:
                - 0.1
                - 2.0
            - kind: kd_random_grayscale
              p: 0.2
            - kind: kd_random_solarize
              p: 0.2
              threshold: 128
            - kind: kd_image_net_norm
model:
  kind: mae_contheads_vit
  encoder:
    kind: vit.masked_encoder
    patch_size: 14
    embedding_dim: 1280
    depth: 32
    attention_heads: 16
    is_frozen: true
    initializer:
      checkpoint: last
      kind: previous_run_initializer
      model_name: mae_contheads_vit.encoder
      stage_id: ???
      stage_name: stage1_mae
  contrastive_heads:
    nnclr:
      kind: contrastive_heads.nnclr_head
      proj_hidden_dim: 2048
      pred_hidden_dim: 4096
      output_dim: 256
      queue_size: 65536
      temperature: 0.15
      pooling:
        kind: class_token
      optim:
        kind: adamw
        lr: 0.0001
        betas:
          - 0.9
          - 0.95
        weight_decay: 1.0e-05
        schedule:
          - end_percent: 20
            exclude_first: true
            exclude_last: true
            kind: linear_increasing
          - exclude_last: true
            kind: cosine_decreasing
trainer:
  kind: mae_contheads_vit_trainer
  max_epochs: 20
  effective_batch_size: 512
  precision: bfloat16
  mask_generator:
    kind: random_mask_generator
    mask_ratio: 0.0
  normalize_pixels: true
  log_every_n_epochs: 1
  loggers:
    - every_n_samples: 65536
      kind: group_update_output_logger
      pattern: nn_accuracy
    - every_n_epochs: 1
      kind: group_update_output_logger
      pattern: nn_accuracy
    - kind: checkpoint_logger
      every_n_epochs: 10
    - kind: ema_logger
      every_n_epochs: 10
      model_paths:
        - encoder
      target_factors:
        - 0.9999
