stage_name: stage2
datasets:
  train:
    kind: torchvision_dataset_wrapper
    dataset_identifier: cifar10
    num_classes: 10
    torchvision_args:
      kind: CIFAR10
      train: true
      download: false
    sample_wrappers:
      - kind: multi_view_wrapper
        transforms:
          - - interpolation: bicubic
              kind: kd_random_resized_crop
              scale:
                - 0.1
                - 1.0
              size: 32
            - kind: kd_random_horizontal_flip
            - brightness: 0.4
              contrast: 0.4
              hue: 0.1
              kind: kd_random_color_jitter
              p: 0.8
              saturation: 0.2
            - kind: kd_gaussian_blur_pil
              sigma:
                - 0.1
                - 2.0
            - kind: kd_random_grayscale
              p: 0.2
            - kind: kd_cifar10_norm
          - - interpolation: bicubic
              kind: kd_random_resized_crop
              scale:
                - 0.1
                - 1.0
              size: 32
            - kind: kd_random_horizontal_flip
            - brightness: 0.4
              contrast: 0.4
              hue: 0.1
              kind: kd_random_color_jitter
              p: 0.8
              saturation: 0.2
            - kind: kd_random_gaussian_blur_pil
              p: 0.1
              sigma:
                - 0.1
                - 2.0
            - kind: kd_random_grayscale
              p: 0.2
            - kind: kd_random_solarize
              p: 0.2
              threshold: 128
            - kind: kd_cifar10_norm
model:
  kind: mae_contheads_vit
  encoder:
    kind: vit.masked_encoder
    patch_size: 4
    embedding_dim: 192
    depth: 12
    attention_heads: 3
    is_frozen: true
    initializer:
      checkpoint: last
      kind: previous_run_initializer
      model_name: mae_contheads_vit.encoder
      stage_id: f1i2h9lv
      stage_name: stage1_mae
  contrastive_heads:
    nnclr:
      kind: contrastive_heads.nnclr_head
      proj_hidden_dim: 512
      pred_hidden_dim: 1024
      output_dim: 64
      queue_size: 65536
      temperature: 0.15
      pooling:
        kind: mean_patch
      optim:
        kind: adamw
        lr: 0.0000125
        betas:
          - 0.9
          - 0.95
        schedule:
          - end_percent: 20
            exclude_first: true
            exclude_last: true
            kind: linear_increasing
          - exclude_last: true
            kind: cosine_decreasing
trainer:
  kind: mae_contheads_vit_trainer
  max_epochs: 65
  effective_batch_size: 128
  precision: bfloat16
  mask_generator:
    kind: random_mask_generator
    mask_ratio: 0.0
  normalize_pixels: true
  log_every_n_epochs: 1
  loggers:
    - kind: group_update_output_logger
      every_n_samples: 65536
      pattern: nn_accuracy
    - kind: group_update_output_logger
      every_n_epochs: 1
      pattern: nn_accuracy
    - kind: checkpoint_logger
      every_n_epochs: 10
    - kind: ema_logger
      every_n_epochs: 10
      model_paths:
        - encoder
      target_factors:
        - 0.9999
